# frontend/Dockerfile
FROM node:20 AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Copy build into shared volume at runtime
FROM busybox AS copy
COPY --from=builder /app/dist /usr/share/nginx/html
