# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV SSL False

# Set the working directory
WORKDIR /code

# Copy the requirements file and install dependencies
COPY requirements.txt .

RUN pip config set global.trusted-host \
    "pypi.org files.pythonhosted.org pypi.python.org" \ 
    --trusted-host=pypi.python.org \ 
    --trusted-host=pypi.org \ 
    --trusted-host=files.pythonhosted.org

RUN pip install -r requirements.txt

RUN apt-get update



# Copy the project files
COPY . .
