# Generated by Django 5.2.4 on 2025-07-18 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_ico_alter_customuser_rc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PSC',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(code='invalid_psc', message='PSČ musí obsahovat přesně 5 číslic.', regex='^\\d{5}$')]),
        ),
    ]
