# Generated by Django 5.2.4 on 2025-08-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otc',
        ),
    ]
