# Generated by Django 5.2.4 on 2025-07-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bank_acc',
        ),
        migrations.AddField(
            model_name='customuser',
            name='GDPR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='RC',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account',
            field=models.CharField(blank=True, null=True),
        ),
    ]
