# Generated by Django 5.2.4 on 2025-07-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_bank_acc_customuser_gdpr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ICO',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='PSC',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
