# Generated by Django 5.2.4 on 2025-07-21 10:53

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', account.models.CustomUserActiveManager()),
                ('all_objects', account.models.CustomUserAllManager()),
            ],
        ),
    ]
