# Generated by Django 5.2.4 on 2025-07-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimeLoginToken',
        ),
    ]
