# Generated by Django 5.2.4 on 2025-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PSC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, null=True),
        ),
    ]
