# Generated by Django 5.2.4 on 2025-07-18 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Název')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis problému')),
                ('status', models.CharField(blank=True, choices=[('new', 'Nový'), ('in_progress', 'Řeší se'), ('resolved', 'Vyřešeno'), ('closed', 'Uzavřeno')], default='new', max_length=20, null=True, verbose_name='Stav')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('urgency', models.CharField(blank=True, choices=[('low', 'Nízká'), ('medium', 'Střední'), ('high', 'Vysoká'), ('critical', 'Kritická')], default='medium', max_length=10, null=True, verbose_name='Urgence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRequest_user', to=settings.AUTH_USER_MODEL, verbose_name='Zadavatel')),
            ],
        ),
    ]
