# Generated by Django 5.2.4 on 2025-07-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='category',
            field=models.CharField(blank=True, choices=[('tech', 'Technická chyba'), ('reservation', 'Chyba při rezervaci'), ('payment', 'Problém s platbou'), ('account', 'Problém s účtem'), ('content', 'Nesrovnalost v obsahu'), ('suggestion', 'Návrh na zlepšení'), ('other', 'Jiný')], default='tech', max_length=20, null=True, verbose_name='Kategorie'),
        ),
    ]
