# Generated by Django 5.2.4 on 2025-07-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0002_serviceticket_deleted_at_serviceticket_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceticket',
            name='category',
            field=models.CharField(blank=True, choices=[('tech', 'Technická chyba'), ('reservation', 'Chyba při rezervaci'), ('payment', 'Problém s platbou'), ('account', 'Problém s účtem'), ('content', 'Nesrovnalost v obsahu'), ('suggestion', 'Návrh na zlepšení'), ('other', 'Jiný')], default='tech', max_length=20, verbose_name='Kategorie'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Nový'), ('in_progress', 'Řeší se'), ('resolved', 'Vyřešeno'), ('closed', 'Uzavřeno')], default='new', max_length=20, verbose_name='Stav'),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='urgency',
            field=models.CharField(blank=True, choices=[('low', 'Nízká'), ('medium', 'Střední'), ('high', 'Vysoká'), ('critical', 'Kritická')], default='medium', max_length=10, verbose_name='Urgence'),
        ),
    ]
