# Generated by Django 5.2.4 on 2025-08-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedesk', '0003_alter_serviceticket_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='urgency',
        ),
    ]
