# Generated by Django 5.2.4 on 2025-07-14 12:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='area',
        ),
        migrations.AddField(
            model_name='cell',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='booking.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Město není zadané', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='h',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='squares-imgs/'),
        ),
        migrations.AddField(
            model_name='event',
            name='psc',
            field=models.PositiveIntegerField(default=12345, help_text='Zadejte platné PSČ (5 číslic)', validators=[django.core.validators.MaxValueValidator, django.core.validators.MinValueValidator]),
        ),
        migrations.AddField(
            model_name='event',
            name='square_size',
            field=models.CharField(choices=[('20x45', 'SMP Ostrava-jih'), ('45x55', 'Ostrava Jih'), ('0x0', 'Nedefinováno')], default=((0, 0), 'Nedefinováno'), help_text='Vyberte rozměry náměstí', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='street',
            field=models.CharField(default='Ulice není zadaná', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='w',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='y',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
