# Generated by Django 5.2.4 on 2025-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_event_deleted_at_event_is_deleted_and_more'),
        ('product', '0003_alter_eventproduct_end_selling_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='event_products',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='product.eventproduct'),
        ),
    ]
