# Generated by Django 5.2.4 on 2025-07-16 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_cell_area_cell_event_event_city_event_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='layout_data',
            field=models.JSONField(default=list, help_text='2D layout polí mapy ve formátu React Grid Layout'),
        ),
        migrations.AlterField(
            model_name='event',
            name='psc',
            field=models.PositiveIntegerField(default=12345, help_text='Zadejte platné PSČ (5 číslic)', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
    ]
