# Generated by Django 5.2.4 on 2025-07-16 06:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_event_layout_data_alter_event_psc_delete_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='layout_data',
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, help_text='Cena za m² pro rezervaci', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='MarketSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('empty', 'Nezakoupeno'), ('blocked', 'Zablokovano'), ('taken', 'Plné')], default='empty', max_length=20)),
                ('avilabe_extension', models.FloatField(default=0, help_text='Možnost rozšíření (m2)')),
                ('first_x', models.SmallIntegerField(default=0)),
                ('first_y', models.SmallIntegerField(default=0)),
                ('second_x', models.SmallIntegerField(default=0)),
                ('second_y', models.SmallIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_slot', to='booking.event')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='marketSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.marketslot'),
        ),
    ]
