# Generated by Django 5.2.4 on 2025-07-24 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_event_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='square',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='square_events', to='booking.square'),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, editable=False, help_text='Pořadové číslo prodejního místa na svém Eventu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Neuvádět, pokud chcete, aby se vypočitala automaticky na zakladě ceny za m² prodejního místa a počtu dní rezervace.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='marketSlot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketslot_reservations', to='booking.marketslot'),
        ),
    ]
