# Generated by Django 5.2.4 on 2025-07-29 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_event_square_alter_marketslot_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Cena vypočtena automaticky na zakladě ceny za m² prodejního místa a počtu dní rezervace.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
