# Generated by Django 5.2.4 on 2025-07-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_event_layout_data_reservation_final_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketslot',
            old_name='avilabe_extension',
            new_name='available_extension',
        ),
        migrations.AlterField(
            model_name='event',
            name='square_size',
            field=models.CharField(choices=[('20x45', 'SMP Ostrava-jih'), ('45x55', 'Ostrava Jih'), ('0x0', 'Nedefinováno')], default='0x0', help_text='Vyberte rozměry náměstí', max_length=20),
        ),
    ]
