# Generated by Django 5.2.4 on 2025-07-16 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_avilabe_extension_marketslot_available_extension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('ulice', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('PSC', models.CharField(max_length=5)),
                ('width', models.PositiveIntegerField(default=10)),
                ('height', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='marketslot',
            name='price',
        ),
        migrations.AddField(
            model_name='marketslot',
            name='base_size',
            field=models.FloatField(default=0, help_text='Základní velikost (m2)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='marketslot',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cena za m² pro toto prodejn místo', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='used_extension',
            field=models.FloatField(default=0, help_text='Použité rozšíření (m2)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='grid_resolution',
            field=models.FloatField(help_text='Rozlišení mřížky v metrech (např. 1.0 nebo 2.0)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='h',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='w',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='x',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='y',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='available_extension',
            field=models.FloatField(default=0, help_text='Možnost rozšíření (m2)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketSlot_event', to='booking.event'),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='first_x',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='first_y',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='second_x',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='second_y',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_event', to='booking.event'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='marketSlot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_marketSlot', to='booking.marketslot'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='square',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_on_sqare', to='booking.square'),
        ),
    ]
