# Generated by Django 5.2.4 on 2025-08-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_reservation_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='marketSlot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='market_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='booking.marketslot'),
        ),
    ]
