# Generated by Django 5.2.4 on 2025-07-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_square_remove_marketslot_price_marketslot_base_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='square',
            name='ulice',
        ),
        migrations.AddField(
            model_name='square',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='square',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='square',
            name='PSC',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='square',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
