# Generated by Django 5.2.4 on 2025-07-17 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_square_remove_marketslot_price_marketslot_base_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketslot',
            old_name='first_x',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='marketslot',
            old_name='first_y',
            new_name='y',
        ),
        migrations.RemoveField(
            model_name='marketslot',
            name='second_x',
        ),
        migrations.RemoveField(
            model_name='marketslot',
            name='second_y',
        ),
        migrations.AddField(
            model_name='marketslot',
            name='height',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='marketslot',
            name='width',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
