# Generated by Django 5.2.4 on 2025-08-04 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_reservation_marketslot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='market_slot',
        ),
        migrations.AddField(
            model_name='reservation',
            name='marketSlot',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='marketslot_reservations', to='booking.marketslot'),
            preserve_default=False,
        ),
    ]
