# Generated by Django 5.2.4 on 2025-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_square_ulice_square_name_square_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='grid_collSize',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='square',
            name='grid_cols',
            field=models.PositiveSmallIntegerField(default=45),
        ),
        migrations.AddField(
            model_name='square',
            name='grid_rows',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
