# Generated by Django 5.2.4 on 2025-08-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_reservation_marketslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketslot',
            name='status',
            field=models.CharField(choices=[('allowed', 'Povoleno'), ('blocked', 'Zablokováno')], default='allowed', max_length=20),
        ),
    ]
