# Generated by Django 5.2.4 on 2025-07-17 10:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_square_grid_collsize_square_grid_cols_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketslot',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, help_text='Pořadové číslo prodejního místa na svém Eventu'),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='available_extension',
            field=models.FloatField(default=0, help_text='Možnost rozšíření (m²)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='base_size',
            field=models.FloatField(default=0, help_text='Základní velikost (m²)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='first_x',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='first_y',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cena za m² pro toto prodejní místo. Neuvádět, pokud chcete nechat výchozí cenu za m² na tomto Eventu.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='second_x',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='second_y',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='marketslot',
            name='status',
            field=models.CharField(choices=[('empty', 'Nezakoupeno'), ('blocked', 'Zablokováno'), ('taken', 'Plné')], default='empty', max_length=20),
        ),
    ]
