# Generated by Django 5.2.4 on 2025-08-06 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_reservation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cena vypočtena automaticky na zakladě ceny za m² prodejního místa a počtu dní rezervace.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_to',
            field=models.DateField(),
        ),
    ]
