# Generated by Django 5.2.4 on 2025-08-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_reservation_is_checked_reservation_last_checked_at_and_more'),
        ('booking', '0011_alter_event_end_alter_event_start_and_more'),
    ]

    operations = [
    ]
