# Generated by Django 5.2.4 on 2025-07-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_eventproduct_deleted_at_eventproduct_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventproduct',
            name='end_selling_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='eventproduct',
            name='start_selling_date',
            field=models.DateTimeField(),
        ),
    ]
