name: Django CI via Docker Compose

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-compose-ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Create backend/.env from secrets
      run: |
        mkdir -p backend
        cat <<EOF > backend/.env
        USE_PRODUCTION_DB=${{ secrets.USE_PRODUCTION_DB }}
        DATABASE_ENGINE=${{ secrets.DATABASE_ENGINE }}
        DATABASE_HOST=${{ secrets.DATABASE_HOST }}
        DATABASE_PORT=${{ secrets.DATABASE_PORT }}
        DATABASE_NAME=${{ secrets.DATABASE_NAME }}
        DATABASE_USER=${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
        DEBUG=${{ secrets.DEBUG }}
        DEFAULT_FROM_EMAIL_DEV=${{ secrets.DEFAULT_FROM_EMAIL_DEV }}
        EMAIL_HOST_DEV=${{ secrets.EMAIL_HOST_DEV }}
        EMAIL_PORT_DEV=${{ secrets.EMAIL_PORT_DEV }}
        EMAIL_USER_DEV=${{ secrets.EMAIL_USER_DEV }}
        EMAIL_USER_PASSWORD_DEV=${{ secrets.EMAIL_USER_PASSWORD_DEV }}
        FRONTEND_URL=${{ secrets.FRONTEND_URL }}
        EOF

    - name: Build and run Docker Compose
      run: docker-compose up -d --build

    - name: Wait for containers to stabilize
      run: sleep 10

    - name: Run migrations inside container
      run: docker-compose exec -T web python manage.py migrate

    - name: Check for missing migrations
      run: docker-compose exec -T web python manage.py makemigrations --check --dry-run

    - name: Populate DB (faker)
      run: docker-compose exec -T web python populate_db.py

    - name: Run Django tests
      run: docker-compose exec -T web python manage.py test

    - name: Stop and remove containers
      if: always()
      run: docker-compose down
